amigos/urls.py
from django.urls import path
from . import views

app_name = 'psiuAmigos'
urlpatterns = [
    path('', views.index, name='index'),
    path('todos', views.todos, name='todos'),
    path('pendentes', views.pendentes, name='pendentes'),
    path('agregar', views.agregar, name='agregar'),
    path('recente', views.recente, name='recente'),
    path('aceitar/<id>', views.aceitar, name='aceitar'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from psiu import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('psiu/', include('psiu.urls')),
    path('psiuChat/', include('psiuChat.urls')),
    path('psiuAmigos/', include('amigos.urls', namespace='amigos')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

psiu/urls.py
from django.urls import path
from . import views

app_name = 'psiu'
urlpatterns = [
    path('', views.home, name='main'),
    path('user_info/<id>', views.user_info, name='user_info'),
    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas_academicas/', views.ligas_academicas, name='ligas_academicas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),
    path('criar/', views.register_request, name='criar'),
    path('criar_perfil/',views.perfil_request, name='criar_perfil'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('modificar/', views.modificar_request, name='modificar'),
    path('salas/', views.salas, name='Sala de chat'),
    path('ligas_oficiais/', views.listaAtividades, name='ligas_oficiais'),
    path('modificar_perfil/', views.modificar_perfil, name='modificar_perfil'),
    path('modificar_atividade/', views.modificar_atividade, name='modificar_atividade'),
    path('ajuda/', views.ajuda, name='ajuda'),

    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas/', views.listaAtividades, name='ligas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),

    #criar
    path('criar_carona/',views.criar_atividade, name='criar_carona'),
    path('criar_estudos/',views.criar_atividade, name='criar_estudos'),
    path('criar_conhecer/',views.criar_atividade, name='criar_conhecer'),
    path('criar_liga/',views.criar_atividade, name='criar_ligas'),
    path('criar_extracurricular/',views.criar_atividade, name='criar_extracurricular'),
    path('darkMode/', views.darkMode_request, name='darkMode'),
    path('miopiaMode/', views.miopiaMode_request, name='miopiaMode'),
    path('corMode/', views.corMode_request, name='corMode'),
    
    #deletar
    path('apagar_carona/<id>',views.apagar_atividade, name='apagar_carona'),
    path('apagar_estudos/<id>',views.apagar_atividade, name='apagar_estudos'),
    path('apagar_extracurricular/<id>',views.apagar_atividade, name='apagar_extracurricular'),
    path('apagar_conhecer/<id>',views.apagar_atividade, name='apagar_conhecer'),
    path('apagar_liga/<id>',views.apagar_atividade, name='apagar_liga'),

    #participar
    path('participar_carona/<id>',views.participar_atividade, name='participar_carona'),
    path('participar_estudos/<id>',views.participar_atividade, name='participar_estudos'),
    path('participar_extracurricular/<id>',views.participar_atividade, name='participar_extracurricular'),
    path('participar_conhecer/<id>',views.participar_atividade, name='participar_conhecer'),
    path('participar_liga/<id>',views.participar_atividade, name='participar_liga'),
    path('participar_liga_oficial/<id>',views.participar_atividade, name='participar_liga_oficial'),

    #sair
    path('sair_carona/<id>',views.sair_atividade, name='sair_carona'),
    path('sair_estudos/<id>',views.sair_atividade, name='sair_estudos'),
    path('sair_extracurricular/<id>',views.sair_atividade, name='sair_extracurricular'),
    path('sair_conhecer/<id>',views.sair_atividade, name='sair_conhecer'),
    path('sair_liga/<id>',views.sair_atividade, name='sair_liga'),
    path('sair_liga_oficial/<id>',views.sair_atividade, name='sair_liga_oficial'),

    #views
    path('info_carona/<id>', views.info_atividade, name='view_carona'),
    path('info_estudos/<id>', views.info_atividade, name='info_estudos'),
    path('info_extracurricular/<id>', views.info_atividade, name='info_extracurricular'),
    path('info_liga/<id>', views.info_atividade, name='info_liga'),
    path('info_liga_oficial/<id>',views.info_atividade, name='info_liga_oficial'),
    path('info_conhecer/<id>', views.info_atividade, name='info_conhecer'),
]

psiuChat/urls.py
from django.urls import path
from . import views

app_name = 'psiuChat'
urlpatterns = [
    path('', views.chatHome, name='chatHome'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

amigos/models.py
from email.policy import default
from django.db import models
from psiu.models import User, Perfil
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth.models import User
from psiuChat.models import Room
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Amizade(models.Model):
    amigo1 = models.ManyToManyField(User, related_name="amigo1", default = "")
    amigo2 = models.ManyToManyField(User, related_name="amigo2", default = "")
    sala = models.OneToOneField(Room, on_delete=models.CASCADE,null=True,blank=True)
    data = models.DateField(null = True)

class Solicitude(models.Model):
    user1 = models.ManyToManyField(User, related_name="user1", default = "")
    user2 = models.ManyToManyField(User, related_name="user2", default = "")
    data = models.DateField(null = True)

amigos/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from amigos.models import *
from psiu.models import *
from psiu.urls import *
import amigos
from datetime import datetime  

def index(request):
    return redirect(reverse("amigos:todos"))

meusAmigos = [
        {"nome":"Bob", "descricao":"Bob is cool"},
        {"nome":"Rick", "descricao":"Rick is not cool"},
    ]

def recente(request):
    atividades = get_friends_info(request.user.id)
    
    return render(request,"amigos/recente.html", {"disableSearch":True,"atividades":atividades})

def todos(request):
    userId = request.user.id
    meusAmigos = Amizade.objects.all().filter(amigo1 = userId) | Amizade.objects.all().filter(amigo2 = userId)
    amigos = []
    for amizade in meusAmigos:
        #Check if it is not the user
        amigo = Amizade._meta.get_field("amigo1").value_from_object(amizade)[0]
        if amigo != userId:
            amigo = Amizade._meta.get_field("amigo2").value_from_object(amizade)[0]
        
        perfilAmigo = Perfil.objects.filter(user=amigo)
       
        #img=amigo.img nome=amigo.nome descricao=amigo.descricao link1="link" link2="link"
        sala = getattr(amizade,'sala')
        if sala: sala = sala.name

        amigos.append(perfilAmigo.__dict__ |{
            "nome": getattr(amigo,'username'),
            "bio": getattr(amigo.perfil,'bio'),
            "fotoPerfil" : amigo.perfil.fotoPerfil.url,
            "sala":sala
        })
        
        #print(amigos[-1])
    #return render(request,"base.html")
    return render(request,"amigos/todos.html", {"amigos": amigos,"disableSearch":False})

def pendentes(request):
    userId = request.user.id
    minhasSolicitudes = Solicitude.objects.filter(user2 = userId)
    amigos = []
    for amizade in minhasSolicitudes:
        #Check if it is not the user
        amigo = Solicitude._meta.get_field("user1").value_from_object(amizade)
        if not amigo: break
        amigo = amigo[0]
        perfilAmigo = Perfil.objects.filter(user=amigo)
       
        #img=amigo.img nome=amigo.nome descricao=amigo.descricao link1="link" link2="link"
        amigos.append(perfilAmigo.__dict__ |{
            "solicitude_id": getattr(amizade,"pk"),
            "nome": getattr(amigo,'username'),
            "img" : amigo.perfil.fotoPerfil.url,
        })
    #return render(request,"base.html")
    return render(request,"amigos/pendentes.html", {"amigos": amigos,"disableSearch":True})

def agregar(request):
    #return render(request,"base.html")
    if request.method == 'GET':
        print('get')
    elif request.method == 'POST':
        print('post')
        novaSolicitude = Solicitude.objects.create()
        form = request.POST.dict()
        novaSolicitude.user1.add(request.user.id)
        novaSolicitude.user2.add(form.get('codigo'))
        return render(request,"amigos/agregar.html",{"disableSearch":True,'userId':request.user.id,'alerta':"A solicitação foi enviada com sucesso"})
    return render(request,"amigos/agregar.html",{"disableSearch":True,'userId':request.user.id})

def aceitar(request, id):
    
    solicitude = Solicitude.objects.filter(pk = id)
    if solicitude: solicitude=solicitude[0]
    aux =  Solicitude._meta.get_field("user1").value_from_object(solicitude)[0].__dict__

    idUser = aux["id"]

    print("Solicitação encontrada", idUser)
    sala = Room.objects.create()

    amizade = Amizade.objects.create(sala=sala)

    amizade.amigo1.add(idUser)
    amizade.amigo2.add(request.user.id)

    amizade.save()
    solicitude.delete()

    return redirect(reverse('amigos:pendentes'))

'''
STEPS 
For each friend:
    get the 5 most recents activities(
        for each kind of activity get 5
        #for 1 to 5 compare all kinds to get the most recent one
        mix kinds and sort by date
        extract the top 5
    )
    mix kinds and sort by date
    extract the top 5
'''

def getUserActivity(user):
    activitiesObjects = Atividade.objects.filter(criador_id = user.id)[:5]
    userActivities = []
    for j in activitiesObjects:
        userActivities.append(
            {
                "tipo": getattr(j,'tipo'),
                "user":user.username,
                "data":getattr(j,'dataModificacao'),
            }
        )
 
    return sorted(userActivities,key=lambda x:x["data"],reverse=True)[:5]
#datetime.datetime

nResults = 20
def get_friends_info(id):
    userId = id
    meusAmigos = Amizade.objects.all().filter(amigo1 = userId) | Amizade.objects.all().filter(amigo2 = userId)
    amigos = []
    atividades = []
    for amizade in meusAmigos:
        #Check if it is not the user
        amigo = Amizade._meta.get_field("amigo1").value_from_object(amizade)[0]
        if amigo != userId:
            amigo = Amizade._meta.get_field("amigo2").value_from_object(amizade)[0]
        amigos.append(amigo)
    for i in amigos:
        atividades.extend(getUserActivity(i))
    
    return sorted(atividades,key=lambda x:x["data"],reverse=True)[:20]

templates/amigos/agregar.html
{% extends "amigos/base.html"%}
{% block navbar %}
<nav class="nav nav-pills flex-column flex-sm-row">
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:recente' %}">Recente</a>
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:todos' %}">Todos</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:pendentes' %}">Pendentes</a>
    <a class="flex-sm-fill text-sm-center nav-link active" href="{% url 'amigos:agregar' %}">Agregar</a>
</nav>
{% endblock %}
{% block content %}
<h5>Ingressar</h5>
<form method="post">
    {% csrf_token %}

    <div class="input-group mb-3">
        <input type="text" class="form-control" name="codigo" placeholder="Codigo" aria-label="Recipient's username" aria-describedby="button-addon2">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Enviar Solicitação</button>
    </div>
</form>
<h5>Compartilhar</h5>
<form >
    <div class="input-group mb-3">
        <input type="text" id="userId" class="form-control" value="{{userId}}" aria-describedby="button-addon2" disabled>
        <button class="btn btn-outline-secondary" type="button" id="button-addon2" style="display:none">Copiar</button>
    </div>
</form>
{% endblock %}

templates/amigos/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1">
    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel = "stylesheet" integrity = "sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin = "anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% block head %}
    {% endblock%}

    <title>Psiu Amigos</title>

  </head>
  <body>

    <!-- NAVBAR -->
    <div style="background-color: #6FA8FF;" class="container-fluid p-4 text-black text-center">
        {% include 'includes/menuzinho.html' %}
        <h1>
            <a href="{% url 'amigos:index' %}" style="color: black;text-decoration: none;">Psiu</a>
        </h1>
        <div style="height: 2em;"></div>
        <div class="row position-relative">
            <div class="col ">
                <a href="{% url 'psiu:main' %}" class="link-light lead">< Voltar para Página Inicial</a>
            </div>
            <div class="col">
                {% block image-page %}
                <a href="{% url 'amigos:index' %}">
                    <img src="https://media.discordapp.net/attachments/1004623388758777966/1047490966426243124/apoio-suporte.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
                </a>
                {% endblock %}
            </div>
            <div class="col"></div>

        </div>
        
    </div>
  <div style="height: 60px;"></div>
    <!-- END NAVBAR-->


    <div class="row">
    <div class="col-2"></div>
    <div class="col" style="max-width: 75%;">
        {% block navbar %}
        <nav class="nav nav-pills flex-column flex-sm-row">
            <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="#">Todos</a>
            <a class="flex-sm-fill text-sm-center nav-link" href="#">Pendentes</a>
            <a class="flex-sm-fill text-sm-center nav-link" href="#">Agregar</a>
        </nav>
        {% endblock %}
        <br>
        {% if alerta %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            >> {{ alerta }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}

        {% if not disableSearch %}
        <form action="post">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="nome" placeholder="Nome" aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2"><i class="bi bi-search"></i></button>
            </div>
        </form>
        {% endif %}
        {% block content %}

        {% endblock %}

    </div>
    <div class="col-2"></div>
    </div>
    

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/amigos/pendentes.html
{% extends "amigos/base.html"%}
{% block navbar %}
<nav class="nav nav-pills flex-column flex-sm-row">
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:recente' %}">Recente</a>
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:todos' %}">Todos</a>
    <a class="flex-sm-fill text-sm-center nav-link active" href="{% url 'amigos:pendentes' %}">Pendentes</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:agregar' %}">Agregar</a>
</nav>
{% endblock %}
{% block content %}  
    {% for amigo in amigos%}
        {% url 'amigos:aceitar' amigo.solicitude_id as solicitudeUrl%}
        {% url 'psiu:info_perfil' amigo.user_id as chatUrl%}
        {% include "amigos/includes/amigoOverview.html" with img=amigo.img nome=amigo.nome descricao=amigo.descricao link1=solicitudeUrl link2=amigo.rejeitarLink icon1="bi-check-lg" icon2="bi-x-lg" %}
    {% endfor %}
{% endblock %}

templates/amigos/recente.html
{% extends "amigos/base.html"%}
{% block navbar %}
<nav class="nav nav-pills flex-column flex-sm-row">
    <a class="flex-sm-fill text-sm-center nav-link active" aria-current="page" href="{% url 'amigos:recente' %}">Recente</a>
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:todos' %}">Todos</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:pendentes' %}">Pendentes</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:agregar' %}">Agregar</a>
</nav>
{% endblock %}
{% block content %}  


    {% for atividade in atividades%}
    <div class="vstack gap-2">
        <div class="bg-light">
            >>
            <a href="#" class="link-dark"><b> {{atividade.user | capfirst}}</b></a> 
            <!--{{atividade|default:"crio"}}-->
            criou
            <a href="#" class="link-dark"><b> {{atividade.tipo}}</b></a>
            ,
            <!--há {{tempo|default:"5 minutos"}}-->
            {{ atividade.data|date:'Y-m-d H:i' }}
        </div>
    </div>
    
    {% endfor %}
{% endblock %}

user tipo data

templates/amigos/todos.html
{% extends "amigos/base.html"%}
{% block navbar %}
<nav class="nav nav-pills flex-column flex-sm-row">
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" href="{% url 'amigos:recente' %}">Recente</a>
    <a class="flex-sm-fill text-sm-center nav-link active" aria-current="page" href="{% url 'amigos:todos' %}">Todos</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:pendentes' %}">Pendentes</a>
    <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'amigos:agregar' %}">Agregar</a>
</nav>
{% endblock %}
{% block content %}  
    {% for amigo in amigos%}
    {% url 'psiu:info_perfil' amigo.user_id as perfilUrl%}
    {% url 'psiuChat:room' amigo.sala as chatUrl%}
    {% include "amigos/includes/amigoOverview.html" with img=amigo.fotoPerfil nome=amigo.nome descricao=amigo.bio link1=chatUrl link2=perfilUrl icon1="bi-chat-left" icon2="bi-plus-square"%}
    {% endfor %}
{% endblock %}