amigos/urls.py
from django.urls import path
from . import views

app_name = 'psiuAmigos'
urlpatterns = [
    path('', views.index, name='index'),
    path('todos', views.todos, name='todos'),
    path('pendentes', views.pendentes, name='pendentes'),
    path('agregar', views.agregar, name='agregar'),
    path('recente', views.recente, name='recente'),
    path('aceitar/<id>', views.aceitar, name='aceitar'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from psiu import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('psiu/', include('psiu.urls')),
    path('psiuChat/', include('psiuChat.urls')),
    path('psiuAmigos/', include('amigos.urls', namespace='amigos')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

psiu/urls.py
from django.urls import path
from . import views

app_name = 'psiu'
urlpatterns = [
    path('', views.home, name='main'),
    path('user_info/<id>', views.user_info, name='user_info'),
    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas_academicas/', views.ligas_academicas, name='ligas_academicas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),
    path('criar/', views.register_request, name='criar'),
    path('criar_perfil/',views.perfil_request, name='criar_perfil'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('modificar/', views.modificar_request, name='modificar'),
    path('salas/', views.salas, name='Sala de chat'),
    path('ligas_oficiais/', views.listaAtividades, name='ligas_oficiais'),
    path('modificar_perfil/', views.modificar_perfil, name='modificar_perfil'),
    path('modificar_atividade/', views.modificar_atividade, name='modificar_atividade'),
    path('ajuda/', views.ajuda, name='ajuda'),

    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas/', views.listaAtividades, name='ligas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),

    #criar
    path('criar_carona/',views.criar_atividade, name='criar_carona'),
    path('criar_estudos/',views.criar_atividade, name='criar_estudos'),
    path('criar_conhecer/',views.criar_atividade, name='criar_conhecer'),
    path('criar_liga/',views.criar_atividade, name='criar_ligas'),
    path('criar_extracurricular/',views.criar_atividade, name='criar_extracurricular'),
    path('darkMode/', views.darkMode_request, name='darkMode'),
    path('miopiaMode/', views.miopiaMode_request, name='miopiaMode'),
    path('corMode/', views.corMode_request, name='corMode'),
    
    #deletar
    path('apagar_carona/<id>',views.apagar_atividade, name='apagar_carona'),
    path('apagar_estudos/<id>',views.apagar_atividade, name='apagar_estudos'),
    path('apagar_extracurricular/<id>',views.apagar_atividade, name='apagar_extracurricular'),
    path('apagar_conhecer/<id>',views.apagar_atividade, name='apagar_conhecer'),
    path('apagar_liga/<id>',views.apagar_atividade, name='apagar_liga'),

    #participar
    path('participar_carona/<id>',views.participar_atividade, name='participar_carona'),
    path('participar_estudos/<id>',views.participar_atividade, name='participar_estudos'),
    path('participar_extracurricular/<id>',views.participar_atividade, name='participar_extracurricular'),
    path('participar_conhecer/<id>',views.participar_atividade, name='participar_conhecer'),
    path('participar_liga/<id>',views.participar_atividade, name='participar_liga'),
    path('participar_liga_oficial/<id>',views.participar_atividade, name='participar_liga_oficial'),

    #sair
    path('sair_carona/<id>',views.sair_atividade, name='sair_carona'),
    path('sair_estudos/<id>',views.sair_atividade, name='sair_estudos'),
    path('sair_extracurricular/<id>',views.sair_atividade, name='sair_extracurricular'),
    path('sair_conhecer/<id>',views.sair_atividade, name='sair_conhecer'),
    path('sair_liga/<id>',views.sair_atividade, name='sair_liga'),
    path('sair_liga_oficial/<id>',views.sair_atividade, name='sair_liga_oficial'),

    #views
    path('info_carona/<id>', views.info_atividade, name='view_carona'),
    path('info_estudos/<id>', views.info_atividade, name='info_estudos'),
    path('info_extracurricular/<id>', views.info_atividade, name='info_extracurricular'),
    path('info_liga/<id>', views.info_atividade, name='info_liga'),
    path('info_liga_oficial/<id>',views.info_atividade, name='info_liga_oficial'),
    path('info_conhecer/<id>', views.info_atividade, name='info_conhecer'),
]

templates/includes/caronaCard.html
<div class="row carona-card">
    <div class="d-grid gap-2 col">

        <a href="{% url 'psiu:view_carona' carona.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5" >
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{carona.nomeUser}}</h5>
                        <p class="card-text">Saindo de: {{carona.localSaida}}<br>Indo para: {{carona.localChegada}}</p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{carona.dataHora}}</p>
                        <p class="card-text">Vagas disponíveis: {{carona.vagas}}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/conhecerCard.html
<div class="row">
    <div class="d-grid gap-2 col">
        <a href="{% url 'psiu:info_conhecer' conhecer.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{conhecer.nomeUser}}</h5>
                        <p class="card-text">{{conhecer.interesses}}</p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{conhecer.dataHora}}</p>
                        <p class="card-text-center">Local: {{conhecer.local}}</p>
                        {% if vagas in i %}
                        <p class="card-text">Vagas {{conhecer.vagas}}</p>
                        {% endif  %}
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/contatoCard.html
<h6>Contato</h6>
    <div class="row">
        <div class="d-grid gap-2 col mx-auto">
            <button class="btn btn-outline-secondary" type="button">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h6 class="text-start">{{contato.nomeUser}}</h6>
                            <br>
                            <p class="card-text-start">
                              {{contato.telefone}}<br>
                              {{contato.instagram}}<br>
                              {{contato.direcao }}</p>
                        </div>
                        
                        <div class="col">
                            <img src="{{contato.image}}" class="rounded-circle" height="100" width="100" style="margin-top:23px">
                        </div>
                    </div>
                    <div class="row">

                    </div>
                    <div class="row">
                        <div class="col">
                        </div>
                        <div class="col">
                            <a href="{% url 'psiu:user_info' contato.id %}">+ Visualizar perfil</a>
                        </div>
                    </div>    
                </div>
            </button>
        </div>
    </div>

templates/includes/estudoCard.html
<div class="row estudo-card">
    <div class="d-grid gap-2 col">
        <a href="{% url 'psiu:info_estudos' estudo.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5" >
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{estudo.nomeUser}}</h5>
                        <p class="card-text">{{estudo.materia}}</p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{estudo.dataHora}}</p>
                        <p class="card-text-center">Local: {{estudo.local}}</p>
                        {% if vagas in i %}
                            <p class="card-text">Vagas {{estudo.vagas}}</p>
                        {% endif  %}
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/extracurrCard.html
<div class="row carona-card">
    <div class="d-grid gap-2 col">

        <a href="{% url 'psiu:info_extracurricular' i.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5" >
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{i.nomeUser}}</h5>
                        <p class="card-text">{{i.atividade}}<br></p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{i.dataHora}}</p>
                        <p class="card-text">Vagas disponíveis: {{i.vagas}}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/ligaCard.html
<div class="row carona-card">
    <div class="d-grid gap-2 col">
        <a href="{% url 'psiu:info_liga' liga.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5" >
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{liga.nome}}</h5>
                        <p class="card-text">{{liga.atividade}}</p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{liga.dataHora}}</p>
                        <p class="card-text">Vagas disponíveis: {{liga.vagas}}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/ligaOficialCard.html
<div class="row liga-card">
    <div class="d-grid gap-2 col">
        <a href="{% url 'psiu:info_liga_oficial' liga.id %}" class="btn btn-outline-secondary mb-4 ms-5 me-5" >
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">{{liga.materia}}</h5>
                        <p class="card-text">{{liga.nome}}</p>
                    </div>
                    <div class="col">
                        <p class="card-text">{{liga.atividade}}</p>
                        <p class="card-text">Vagas disponíveis: {{liga.vagas}}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <br>
</div>

templates/includes/menuzinho.html
<button class="btn position-absolute top-0 start-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
    <img src="https://media.discordapp.net/attachments/1004623388758777966/1044246183733895308/unknown.png" height="30" width="30">
</button>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <img src="https://cdn.discordapp.com/attachments/1004623388758777966/1047362170385608764/image.png" height="75" width="75">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Psiu</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="container">
            <div class="row mb-4">
                <div class="col">
                    <a id="home-link" class="btn btn-white" href="{% url 'psiu:main' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033925137378066442/house.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Pagina Inicial
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="carona-link" class="btn btn-white" href="{% url 'psiu:carona' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033926816026611712/parking.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Carona
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="grupo-estudos-link" class="btn btn-white" href="{% url 'psiu:grupo_estudos' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033926469824561252/library.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Grupo de Estudos
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="extracurriculares-link" class="btn btn-white" href="{% url 'psiu:extracurriculares' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033926121827340378/basket-ball.png" height="75" width="75"></a>
                </div>
                <div class="col mt-3">
                    Atividades Extracurriculares
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="ligas-academicas-link" class="btn btn-white" href="{% url 'psiu:ligas_academicas' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033927490936250430/medal.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Ligas Academicas
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="conhecer-pessoas-link" class="btn btn-white" href="{% url 'psiu:conhecer_pessoas' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1033927869719658616/communication.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Conhecer Pessoas
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="modificar-perfil-link" class="btn btn-white" href="{% url 'amigos:todos' %}" role="button"><img src="https://media.discordapp.net/attachments/1004623388758777966/1047490966426243124/apoio-suporte.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Amigos
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a id="modificar-perfil-link" class="btn btn-white" href="{% url 'psiu:modificar_perfil' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1009800857631592489/1036480038025056286/settings.png" height="75" width="75"></a>
                </div>
                <div class="col mt-4">
                    Modificar Perfil
                </div>
            </div>
        </div>
    </div>
</div>