project/urls.py
from django.contrib import admin
from django.urls import path, include
from psiu import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('psiu/', include('psiu.urls')),
    path('psiuChat/', include('psiuChat.urls')),
    path('psiuAmigos/', include('amigos.urls', namespace='amigos')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

psiu/urls.py
from django.urls import path
from . import views

app_name = 'psiu'
urlpatterns = [
    path('', views.home, name='main'),
    path('user_info/<id>', views.user_info, name='user_info'),
    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas_academicas/', views.ligas_academicas, name='ligas_academicas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),
    path('criar/', views.register_request, name='criar'),
    path('criar_perfil/',views.perfil_request, name='criar_perfil'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('modificar/', views.modificar_request, name='modificar'),
    path('salas/', views.salas, name='Sala de chat'),
    path('ligas_oficiais/', views.listaAtividades, name='ligas_oficiais'),
    path('modificar_perfil/', views.modificar_perfil, name='modificar_perfil'),
    path('modificar_atividade/', views.modificar_atividade, name='modificar_atividade'),
    path('ajuda/', views.ajuda, name='ajuda'),

    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas/', views.listaAtividades, name='ligas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),

    #criar
    path('criar_carona/',views.criar_atividade, name='criar_carona'),
    path('criar_estudos/',views.criar_atividade, name='criar_estudos'),
    path('criar_conhecer/',views.criar_atividade, name='criar_conhecer'),
    path('criar_liga/',views.criar_atividade, name='criar_ligas'),
    path('criar_extracurricular/',views.criar_atividade, name='criar_extracurricular'),
    path('darkMode/', views.darkMode_request, name='darkMode'),
    path('miopiaMode/', views.miopiaMode_request, name='miopiaMode'),
    path('corMode/', views.corMode_request, name='corMode'),
    
    #deletar
    path('apagar_carona/<id>',views.apagar_atividade, name='apagar_carona'),
    path('apagar_estudos/<id>',views.apagar_atividade, name='apagar_estudos'),
    path('apagar_extracurricular/<id>',views.apagar_atividade, name='apagar_extracurricular'),
    path('apagar_conhecer/<id>',views.apagar_atividade, name='apagar_conhecer'),
    path('apagar_liga/<id>',views.apagar_atividade, name='apagar_liga'),

    #participar
    path('participar_carona/<id>',views.participar_atividade, name='participar_carona'),
    path('participar_estudos/<id>',views.participar_atividade, name='participar_estudos'),
    path('participar_extracurricular/<id>',views.participar_atividade, name='participar_extracurricular'),
    path('participar_conhecer/<id>',views.participar_atividade, name='participar_conhecer'),
    path('participar_liga/<id>',views.participar_atividade, name='participar_liga'),
    path('participar_liga_oficial/<id>',views.participar_atividade, name='participar_liga_oficial'),

    #sair
    path('sair_carona/<id>',views.sair_atividade, name='sair_carona'),
    path('sair_estudos/<id>',views.sair_atividade, name='sair_estudos'),
    path('sair_extracurricular/<id>',views.sair_atividade, name='sair_extracurricular'),
    path('sair_conhecer/<id>',views.sair_atividade, name='sair_conhecer'),
    path('sair_liga/<id>',views.sair_atividade, name='sair_liga'),
    path('sair_liga_oficial/<id>',views.sair_atividade, name='sair_liga_oficial'),

    #views
    path('info_carona/<id>', views.info_atividade, name='view_carona'),
    path('info_estudos/<id>', views.info_atividade, name='info_estudos'),
    path('info_extracurricular/<id>', views.info_atividade, name='info_extracurricular'),
    path('info_liga/<id>', views.info_atividade, name='info_liga'),
    path('info_liga_oficial/<id>',views.info_atividade, name='info_liga_oficial'),
    path('info_conhecer/<id>', views.info_atividade, name='info_conhecer'),
]

psiu/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from psiuChat.models import Room


class Atividade(models.Model):
  criador = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
  sala = models.OneToOneField(Room, on_delete=models.CASCADE,null=True,blank=True)
  localSaida = models.CharField(max_length=30,null=True, blank=True)
  localChegada = models.CharField(max_length=30,null=True, blank=True)
  dataHora = models.DateTimeField(auto_now_add=False, blank=True, null=True)#Just to prove it
  vagas = models.IntegerField(default=4,null=True)
  adicionais = models.CharField(max_length=254, blank=True, default='')
  dataModificacao = models.DateTimeField(auto_now_add=True, blank=False)
  materia = models.CharField(max_length=10,blank=True)
  local = models.CharField(max_length=30,blank=True)
  nome = models.CharField(max_length=30,blank=True)
  atividade = models.CharField(max_length=30,blank=True)
  interesses = models.CharField(max_length=30,blank=True)

  tipo = models.CharField(max_length=15)

  def get_readonly_fields(self, request, obj=None):
    return [f.name for f in self._meta.get_fields()]


class ParticipacaoAtividade(models.Model):
  id_participante = models.ForeignKey(User, on_delete=models.CASCADE)
  id_grupo = models.ForeignKey(Atividade, on_delete=models.CASCADE)
  rol = models.CharField(max_length=30,blank=True)
  dataModificacao = models.DateTimeField(auto_now_add=True, blank=False)

from django.contrib.auth.backends import ModelBackend, UserModel
from django.db.models import Q

class EmailBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try: #to allow authentication through phone number or any other field, modify the below statement
            user = UserModel.objects.get(Q(username__iexact=username) | Q(email__iexact=username))
        except UserModel.DoesNotExist:
            UserModel().set_password(password)
        except MultipleObjectsReturned:
            return User.objects.filter(email=username).order_by('id').first()
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user

    def get_user(self, user_id):
        try:
            user = UserModel.objects.get(pk=user_id)
        except UserModel.DoesNotExist:
            return None

        return user if self.user_can_authenticate(user) else None


class Perfil(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  bio = models.CharField(max_length=30,default='')
  fotoPerfil = models.ImageField(upload_to='images/',default='images/default.png')
  instagram = models.CharField(max_length=20,default='')
  twitter = models.CharField(max_length=15,default='')
  darkMode = models.BooleanField(default=False)
  dataCriacao = models.DateTimeField(auto_now_add=True, blank=False)
  miopiaMode = models.BooleanField(default=False)
  dataModificacao = models.DateTimeField(auto_now_add=True, blank=False)
  corMode = models.BooleanField(default=False)

  def get_readonly_fields(self, request, obj=None):
    return [f.name for f in self._meta.get_fields()]

psiu/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import *
from .models import *

# Create your forms here.

class NewUserForm(UserCreationForm):

    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={"class": "form-control"}))
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'Username',"class": "form-control"})
        self.fields['first_name'].widget.attrs.update({"class": "form-control"})
        self.fields['last_name'].widget.attrs.update({"class": "form-control"})
        self.fields['password1'].widget.attrs.update({"class": "form-control"})
        self.fields['password2'].widget.attrs.update({"class": "form-control"})


class ModificarPerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ('fotoPerfil','bio','twitter','instagram')

    def __init__(self, user, *args, **kwargs):
        #self.user = user
        #user.objects.get(place=p1)
        super().__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs.update({'placeholder': "Bio","class": "form-control"})


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ('fotoPerfil','bio','instagram','twitter')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fotoPerfil'].widget.attrs.update({"class": "form-control"})
        self.fields['bio'].widget.attrs.update({"class": "form-control"})
        self.fields['instagram'].widget.attrs.update({"class": "form-control"})
        self.fields['twitter'].widget.attrs.update({"class": "form-control"})

class caronaFilter(forms.ModelForm):
    class Meta:
        model = Atividade
        fields = ('localSaida', 'localChegada', 'dataHora', 'vagas', 'adicionais')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['criador'].widget.attrs.update({"class": "form-control"})
        self.fields['localSaida'].widget.attrs.update({"class": "form-control"})
        self.fields['localChegada'].widget.attrs.update({"class": "form-control"})
        self.fields['dataHora'].widget.attrs.update({"class": "form-control"})
        self.fields['vagas'].widget.attrs.update({"class": "form-control"})
        self.fields['adicionais'].widget.attrs.update({"class": "form-control"})

class estudosFilter(forms.ModelForm):
    class Meta:
        model = Atividade
        fields = ('materia', 'local', 'dataHora', 'vagas', 'adicionais')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['criador'].widget.attrs.update({"class": "form-control"})
        self.fields['materia'].widget.attrs.update({"class": "form-control"})
        self.fields['local'].widget.attrs.update({"class": "form-control"})
        self.fields['dataHora'].widget.attrs.update({"class": "form-control"})
        self.fields['vagas'].widget.attrs.update({"class": "form-control"})
        self.fields['adicionais'].widget.attrs.update({"class": "form-control"})

class extraFilter(forms.ModelForm):
    class Meta:
        model = Atividade
        fields = ('atividade', 'local', 'dataHora', 'vagas', 'adicionais')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['atividade'].widget.attrs.update({"class": "form-control"})
        self.fields['local'].widget.attrs.update({"class": "form-control"})
        self.fields['dataHora'].widget.attrs.update({"class": "form-control"})
        self.fields['vagas'].widget.attrs.update({"class": "form-control"})
        self.fields['adicionais'].widget.attrs.update({"class": "form-control"})

class newParticipante(forms.ModelForm):
    class Meta:
        model = ParticipacaoAtividade
        fields = ('id_participante', 'rol')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['id_participante'].widget.attrs.update({"class": "form-control"})
        self.fields['rol'].widget.attrs.update({"class": "form-control"})

class ligasFilter(forms.ModelForm):
    class Meta:
        model = Atividade
        fields = ('nome', 'atividade', 'local', 'dataHora', 'vagas')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['criador'].widget.attrs.update({"class": "form-control"})
        self.fields['nomeLiga'].widget.attrs.update({"class": "form-control"})
        self.fields['atividade'].widget.attrs.update({"class": "form-control"})
        self.fields['local'].widget.attrs.update({"class": "form-control"})
        self.fields['dataHora'].widget.attrs.update({"class": "form-control"})
        self.fields['vagas'].widget.attrs.update({"class": "form-control"})

psiu/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import *
from django.contrib.auth import login, authenticate
from django.contrib import messages
from psiu.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_datetime
from .viewsFolder.user_info import *
from .viewsFolder.views_common import *
from .viewsFolder.login import *
from .viewsFolder.darkModeMiopia import *
from .viewsFolder.atividade_views import *

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        return redirect(reverse('psiu:login'))

def main(request):
    if request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        return redirect(reverse('psiu:login'))

def modificar_perfil(request):
    return render(request, 'psiu/modificar_perfil.html')

def modificar_atividade(request):
    return render(request, 'psiu/modificar_atividade.html')

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, "Registration successful.")
            return redirect(reverse('psiu:criar_perfil'))

        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request, "psiu/criar.html", {"criar_form":form})

def perfil_request(request):
    if request.method == "POST":
        profile_form = PerfilForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect("home")

        messages.error(request, "Unsuccessful registration. Invalid information.")
    profile_form = PerfilForm()
    return render (request, "psiu/criar_perfil.html", {'profile_form': profile_form})

def logout_request(request):
    
    if request.user.is_authenticated:
        logout(request)
    return redirect(reverse('psiu:login'))

def modificar_request(request):
    if request.method == "POST":
        form = ModificarPerfilForm(request.POST, request.FILES, request.user)
        if form.is_valid():
            form.save()
        return redirect(reverse('psiu:user_info'))
    messages.error(request, "Unsuccessful registration. Invalid information.")
    form = ModificarPerfilForm(request.user)

    return render(request, "psiu/modificar.html", {"form":form})

def update_user_social_data(strategy, *args, **kwargs):
  response = kwargs['response']
  backend = kwargs['backend']
  user = kwargs['user']

  if response['fotoPerfil']:
    url = response['fotoPerfil']
    userProfile_obj = UserProfile()
    userProfile_obj.user = user
    userProfile_obj.picture = url
    userProfile_obj.save()

@login_required
def salas(request):
    salas = Sala.objects.all()
    return render(request, 'psiu/salas.html', {'salas': salas})

def ajuda(request):
    return render(request, 'psiu/ajuda.html')

def ligas_oficiais(request):
    return render(request, 'psiu/ligas_oficiais.html',{'title':'Ligas Oficiais'})

def ligas_academicas(request):
    return render(request, 'psiu/ligas_academicas.html',{'title':'Ligas Academicas'})

templates/psiu/ajuda.html
{% extends 'base.html' %}
{% block image-page %}
    <img src="https://media.discordapp.net/attachments/1004623388758777966/1044755829473161297/unknown.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
{% endblock %}
{% block content %}

<br><br>


<h5>O que é o Psiu e como ele funciona?</h5>
O Psiu é um aplicativo de interação social, que permite que um grupo de pessoas possivelmente desconhecidas possa se encontrar em um lugar e hora específicos com um objetivo comum, que seja estudar, jogar ou conversar.
Ele funciona em um sistema de cards, de localização, de filtro e de chat.
<br><br><br>

<h5>Como posso criar uma atividade?</h5>
Cada seção do aplicativo possui um botão - na parte superior esquerda - que lhe permite criar qualquer atividade. Clique nesse botão e preencha os campos para criar a sua atividade e divirta-se :)
<br><br><br>

<h5>Como posso eliminar/editar uma atividade?</h5>
Se você for o criador da atividade, aparecerá um botão no final da página de informação da sua atividade que lhe permitirá apagá-la ou editá-la.
<br><br><br><br><br>

<center>Não encontrou seu problema? Faça sua pergunta abaixo</center>
<br>

<!--<div class="mb-3">
    <label class="form-label">Nome</label>
    <input type="nome" class="form-control">
</div>
<div class="mb-3">
    <label class="form-label">E-mail</label>
    <input type="email" class="form-control">
</div>-->
<div class="mb-3">
    <textarea class="form-control" rows="3" placeholder="Mande sua dúvida..."></textarea>
</div>
<a href="" class="btn btn-primary">Enviar</a>

{% endblock %}

templates/psiu/carona.html
{% extends 'base.html' %}
{% block image-page %}
    <img src="https://cdn.discordapp.com/attachments/1004623388758777966/1019419664142581821/unknown.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
{% endblock %}
{% block content %}

<a href="{% url 'psiu:criar_carona' %}">+ Adicionar carona</a>


<!doctype html>
<html lang = "pt-br">

<div class = "text-center" style = "color: rgba(0,0,0,1)">
    <div class="row">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
            <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#fitro_form">
                Filtrar por ↓
            </button>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="center">
            <div class="input-group mb-3 ms-4">
                <input type="text" class="form-control" placeholder="Barra de pesquisa" aria-label="Recipient's username" aria-describedby="basic-addon2" width="100">
                <button class="btn btn-outline-secondary me-5" type="button" id="button-addon2">P</button>
              </div>
        </div>
    </div>
    
</div>

<br>
{% if carona_list %}
    {% for i in carona_list %}
        {% include "includes/caronaCard.html" with carona=i%}       
    {% endfor %}
{% else %}
    Não foram encontradas caronas.
{% endif %}

<!--Modal for filtragem-->
<form method="post">
    {% csrf_token %}
<div class="modal fade" id="fitro_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="fitro_formLabel">Filtro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{fitro_form}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
</div>
</form>
{% endblock  %}

templates/psiu/estudos.html
{% extends 'base.html' %}
{% block image-page %}
    <img src="https://media.discordapp.net/attachments/1004623388758777966/1019419539966013521/unknown.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
{% endblock %}
{% block content %}

<a href="{% url 'psiu:criar_estudos' %}">+ Adicionar grupo de estudo</a>

<!doctype html>
<html lang = "pt-br">

<div class = "text-center" style = "color: rgba(0,0,0,1)">
    <div class="row">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
            <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#fitro_form">
                Filtrar por ↓
            </button>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="center">
            <div class="input-group mb-3 ms-4">
                <input type="text" class="form-control" placeholder="Barra de pesquisa" aria-label="Recipient's username" aria-describedby="basic-addon2" width="100">
                <button class="btn btn-outline-secondary me-5" type="button" id="button-addon2">P</button>
              </div>
        </div>
    </div>
    
</div>

<br>

{% if grupo_estudos %}
    {% for i in grupo_estudos %}
        {% include "includes/estudoCard.html" with estudo=i%}       
    {% endfor %}
{% else %}
    Nao foram encontrados grupos de estudos
{% endif  %}


<!--Modal for filtragem-->
<form method="post">
    {% csrf_token %}
<div class="modal fade" id="fitro_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="fitro_formLabel">Filtro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{fitro_form}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
</div>
</form>

{% endblock  %}

templates/psiu/ligas_academicas.html
{% extends 'base.html' %}
{% block image-page %}
    <img src="https://cdn.discordapp.com/attachments/1004623388758777966/1019419863707557938/unknown.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
{% endblock %}
{% block content %}


<!doctype html>
<html lang = "pt-br">

<div class = "text-center" style = "color: rgba(0,0,0,1)">
    <br><br><br>
    <div class="row">
        <div class="col">
        </div>
        <div class="col">

        </div>
        <div class="col">
            <div class="card" style="width: 25rem;">
                <img src="..." class="card-img-top" alt="">
                <div class="card-body">
                <h5 class="card-title">Eventos oficiais</h5>
                <p class="card-text">Alguns eventos disponibilizados pela PUC</p>
                <a href="{% url 'psiu:ligas_oficiais' %}" class="btn btn-secondary">Ver eventos</a>
                </div>
            </div>
        </div>
        <div class="col"></div>
        <div class="col">
            <div class="card" style="width: 25rem;">
                <img src="..." class="card-img-top" alt="">
                <div class="card-body">
                <h5 class="card-title">Não oficiais</h5>
                <p class="card-text">Crie e participe de eventos acadêmicos</p>
                <a href="{% url 'psiu:ligas' %}" class="btn btn-secondary">Ver eventos</a>
                </div>
            </div>
        </div>
        <div class="col">

        </div>
        <div class="col">

        </div>
    </div>
</div>



{% endblock %}

templates/psiu/ligas_nao_oficiais.html
{% extends 'base.html' %}
{% block image-page %}
    <img src="https://cdn.discordapp.com/attachments/1004623388758777966/1019419863707557938/unknown.png" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
{% endblock %}
{% block content %}

<a href="{% url 'psiu:criar_ligas' %}">+ Adicionar liga acadêmica</a>


<!doctype html>
<html lang = "pt-br">

<div class = "text-center" style = "color: rgba(0,0,0,1)">
    <div class="row">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
            <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#fitro_form">
                Filtrar por ↓
            </button>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="center">
            <div class="input-group mb-3 ms-4">
                <input type="text" class="form-control" placeholder="Barra de pesquisa" aria-label="Recipient's username" aria-describedby="basic-addon2" width="100">
                <button class="btn btn-outline-secondary me-5" type="button" id="button-addon2">P</button>
              </div>
        </div>
    </div>
    
</div>

<br>

{% if ligas_nao_oficiais %}
    {% for i in ligas_nao_oficiais %}
        {% include "includes/ligaCard.html" with liga=i%}       
    {% endfor %}
{% else %}
    Não foram encontradas ligas acadêmicas.
{% endif  %}

<form method="post">
    {% csrf_token %}
<div class="modal fade" id="fitro_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="fitro_formLabel">Filtro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{fitro_form}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
</div>
</form>
{% endblock %}

templates/psiu/modificar.html
{% extends 'base.html' %}
{% block image-page %}
<a href="{% url 'psiu:user_info' %}">
    <img src="{{ user.perfil.fotoPerfil.url }}" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
</a>
{% endblock %}
{% block content %}
{{form.as_p}}
{% endblock  %}

templates/psiu/modificar_perfil.html
{% extends 'base.html' %}
{% block image-page %}
<a href="{% url 'psiu:user_info' request.user.id %}">
    <img src="{{ user.perfil.fotoPerfil.url }}" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
</a>
{% endblock %}
{% block content %}

    <div class="row">
        <a href="{% url 'psiu:darkMode' %}">Modo Escuro</a>
    </div>
    <br>
    <div class="row">
        <a href="{% url 'psiu:miopiaMode' %}">Modo Zoom</a>
    </div>
    <br>
    <div class="row">
        <a href="{% url 'psiu:corMode' %}">Modo Colorido</a>
    </div>

{% endblock %}

templates/psiu/salas.html
{% extends 'base.html' %}

{% block content %}
<div class="'p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg: text-6xl text-white">Salas</h1>
</div>

<div class="w-full flex flex-wrap items-center">
    {%for sala in salas %}
        <div class="w-full lg:w-1/4 px-3 py-3">
            <div class="p-4 bg-white shadow rounded-xl text-center">
                <h2 class="mb-5 text-2xl font-semibold">{{ sala.nome }} </h2>
                <a href="#">Entrar</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
    <script>
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/'
            + roomName
            + '/'
        );
    </script>
{% endblock %}