project/urls.py
from django.contrib import admin
from django.urls import path, include
from psiu import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('psiu/', include('psiu.urls')),
    path('psiuChat/', include('psiuChat.urls')),
    path('psiuAmigos/', include('amigos.urls', namespace='amigos')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

psiu/urls.py
from django.urls import path
from . import views

app_name = 'psiu'
urlpatterns = [
    path('', views.home, name='main'),
    path('user_info/<id>', views.user_info, name='user_info'),
    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas_academicas/', views.ligas_academicas, name='ligas_academicas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),
    path('criar/', views.register_request, name='criar'),
    path('criar_perfil/',views.perfil_request, name='criar_perfil'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('modificar/', views.modificar_request, name='modificar'),
    path('salas/', views.salas, name='Sala de chat'),
    path('ligas_oficiais/', views.listaAtividades, name='ligas_oficiais'),
    path('modificar_perfil/', views.modificar_perfil, name='modificar_perfil'),
    path('modificar_atividade/', views.modificar_atividade, name='modificar_atividade'),
    path('ajuda/', views.ajuda, name='ajuda'),

    path('carona/', views.listaAtividades, name='carona'),
    path('grupo_estudos/', views.listaAtividades, name='grupo_estudos'),
    path('extracurriculares/', views.listaAtividades, name='extracurriculares'),
    path('ligas/', views.listaAtividades, name='ligas'),
    path('conhecer_pessoas/', views.listaAtividades, name='conhecer_pessoas'),

    #criar
    path('criar_carona/',views.criar_atividade, name='criar_carona'),
    path('criar_estudos/',views.criar_atividade, name='criar_estudos'),
    path('criar_conhecer/',views.criar_atividade, name='criar_conhecer'),
    path('criar_liga/',views.criar_atividade, name='criar_ligas'),
    path('criar_extracurricular/',views.criar_atividade, name='criar_extracurricular'),
    path('darkMode/', views.darkMode_request, name='darkMode'),
    path('miopiaMode/', views.miopiaMode_request, name='miopiaMode'),
    path('corMode/', views.corMode_request, name='corMode'),
    
    #deletar
    path('apagar_carona/<id>',views.apagar_atividade, name='apagar_carona'),
    path('apagar_estudos/<id>',views.apagar_atividade, name='apagar_estudos'),
    path('apagar_extracurricular/<id>',views.apagar_atividade, name='apagar_extracurricular'),
    path('apagar_conhecer/<id>',views.apagar_atividade, name='apagar_conhecer'),
    path('apagar_liga/<id>',views.apagar_atividade, name='apagar_liga'),

    #participar
    path('participar_carona/<id>',views.participar_atividade, name='participar_carona'),
    path('participar_estudos/<id>',views.participar_atividade, name='participar_estudos'),
    path('participar_extracurricular/<id>',views.participar_atividade, name='participar_extracurricular'),
    path('participar_conhecer/<id>',views.participar_atividade, name='participar_conhecer'),
    path('participar_liga/<id>',views.participar_atividade, name='participar_liga'),
    path('participar_liga_oficial/<id>',views.participar_atividade, name='participar_liga_oficial'),

    #sair
    path('sair_carona/<id>',views.sair_atividade, name='sair_carona'),
    path('sair_estudos/<id>',views.sair_atividade, name='sair_estudos'),
    path('sair_extracurricular/<id>',views.sair_atividade, name='sair_extracurricular'),
    path('sair_conhecer/<id>',views.sair_atividade, name='sair_conhecer'),
    path('sair_liga/<id>',views.sair_atividade, name='sair_liga'),
    path('sair_liga_oficial/<id>',views.sair_atividade, name='sair_liga_oficial'),

    #views
    path('info_carona/<id>', views.info_atividade, name='view_carona'),
    path('info_estudos/<id>', views.info_atividade, name='info_estudos'),
    path('info_extracurricular/<id>', views.info_atividade, name='info_extracurricular'),
    path('info_liga/<id>', views.info_atividade, name='info_liga'),
    path('info_liga_oficial/<id>',views.info_atividade, name='info_liga_oficial'),
    path('info_conhecer/<id>', views.info_atividade, name='info_conhecer'),
]

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script>
        
    </script>

    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
    <title>My Psiu App</title>
    {% endif %}

</head>
<body onload="mudarModo1(), mudarModo2(), mudarModo3()"  style="background-color: #FFFFFF !important;">
    <!-- NAVBAR -->
    <div class="container-fluid p-4 text-black text-center" id="divinha">
        {% include "includes/menuzinho.html" %}
        <img src="https://cdn.discordapp.com/attachments/1004623388758777966/1047362170385608764/image.png" height="75" width="75">
        <h1>
            <a href="{% url 'psiu:main' %}" style="color: black;text-decoration: none;">Psiu!</a>
        </h1>
        <br>
        <br>
        <div class="position-relative">
            {% block image-page %}
            <a href="{% url 'psiu:main' %}">
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAMFBMVEXp7vG6vsG3u77s8fTCxsnn7O/f5OfFyczP09bM0dO8wMPk6ezY3eDd4uXR1tnJzdBvAX/cAAACVElEQVR4nO3b23KDIBRA0ShGU0n0//+2KmO94gWZ8Zxmr7fmwWEHJsJUHw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwO1MHHdn+L3rIoK6eshsNJ8kTaJI07fERPOO1Nc1vgQm2oiBTWJ+d8+CqV1heplLzMRNonED+4mg7L6p591FC+133/xCRNCtd3nL9BlxWP++MOaXFdEXFjZ7r8D9l45C8y6aG0cWtP/SUGhs2d8dA/ZfGgrzYX+TVqcTNRRO9l+fS5eSYzQs85psUcuzk6igcLoHPz2J8gvzWaH/JLS+95RfOD8o1p5CU5R7l5LkfKEp0mQ1UX7hsVXqDpRrifILD/3S9CfmlUQFhQfuFu0STTyJ8gsP3PH7GVxN1FC4t2sbBy4TNRTu7LyHJbqaqKFw+/Q0ncFloo7CjRPwMnCWqKXQZ75El4nKC9dmcJaou9AXOE5UXbi+RGeJygrz8Uf+GewSn9uXuplnWDZJ7d8f24F/s6iq0LYf9olbS3Q8i5oKrRu4S9ybwaQ/aCkqtP3I28QDgeoK7TBya/aXqL5COx67PTCD2grtdOwH+pQV2r0a7YVBgZoKwwIVFQYG6ikMDVRTGByopjD8ATcKb0UhhRTe77sKs2DV7FKSjId18TUEBYVyLhUThWfILHTDqmI85/2RWWjcE/bhP6OD7maT3h20MHsA47JC3PsW0wcwLhv9t0OOPOIkCn21y2bXXwlyylxiYMPk1SuCSmpfK8bNQvIrpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwNX4BCbAju9/X67UAAAAASUVORK5CYII=" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
            </a>

            {% endblock %}
        </div>
    </div>
    <div style="height: 50px;"></div>
    <!-- END OF NAVBAR-->

    <div class="container text">
        {% if title %}

        <center>
            <p>{{title}}</p>
        </center>

        {% endif %}
        <!--<div class="container-fluid mt-5" style="max-width: 80%">-->
        <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
        {% block content %}
        {% endblock  %}
        {% block contato %}
        {% endblock  %}
        <script>
            function mudarModo1() {
                var modo = "{{isDarkMode}}"
                if (modo == "True") {
                    document.body.style.background = "#404040"
                    document.body.style.color = "#FFFFFF";
                }
                else {
                    document.body.style.background = "#FFFFFF";
                    document.body.style.color = "#404040";
                }
            }

            function mudarModo2() {
                var modo = "{{isMiopiaMode}}"
                if (modo == "True") {
                    document.body.style.fontSize = "2rem"
                }
                else {
                    document.body.style.fontSize = "1rem"
                }
            }

            function mudarModo3() {
                var modo = "{{isCorMode}}"
                if (modo == "True") {
                    document.getElementById("divinha").style.backgroundColor = "#CC92F8"
                    document.getElementById("offcanvasExample").style.backgroundColor = "#CC92F8"
                }
                else {
                    document.getElementById("divinha").style.backgroundColor = "#6FA8FF"
                    document.getElementById("offcanvasExample").style.backgroundColor = "#6FA8FF"
                }
            }
        </script>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

<a href="{% url 'psiu:ajuda' %}" class="btn position-absolute bottom end-0"><img src="https://media.discordapp.net/attachments/1004623388758777966/1044755829473161297/unknown.png" height="50" width="50"></a>

<a href="{% url 'psiu:logout' %}" class="btn position-absolute top-0 end-0">Sair da conta</a>
</html>
<!-- Towardsdatascience -->

templates/baseChat.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <script>
        
    </script>

    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
    <title>My Psiu App</title>
    {% endif %}

</head>
<body onload="mudarModo1(), mudarModo2()">
    <!-- NAVBAR -->
    <div style="background-color: #6FA8FF;" class="container-fluid p-4 text-black text-center">
        {% include "includes/menuzinho.html" %}
        
        <h1>
            <a href="{% url 'psiu:main' %}" style="color: black;text-decoration: none;">Psiu!</a>
        </h1>
        <br>
        <br>
        <div class="position-relative">
            {% block image-page %}
            <a href="{% url 'psiu:main' %}">
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAMFBMVEXp7vG6vsG3u77s8fTCxsnn7O/f5OfFyczP09bM0dO8wMPk6ezY3eDd4uXR1tnJzdBvAX/cAAACVElEQVR4nO3b23KDIBRA0ShGU0n0//+2KmO94gWZ8Zxmr7fmwWEHJsJUHw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwO1MHHdn+L3rIoK6eshsNJ8kTaJI07fERPOO1Nc1vgQm2oiBTWJ+d8+CqV1heplLzMRNonED+4mg7L6p591FC+133/xCRNCtd3nL9BlxWP++MOaXFdEXFjZ7r8D9l45C8y6aG0cWtP/SUGhs2d8dA/ZfGgrzYX+TVqcTNRRO9l+fS5eSYzQs85psUcuzk6igcLoHPz2J8gvzWaH/JLS+95RfOD8o1p5CU5R7l5LkfKEp0mQ1UX7hsVXqDpRrifILD/3S9CfmlUQFhQfuFu0STTyJ8gsP3PH7GVxN1FC4t2sbBy4TNRTu7LyHJbqaqKFw+/Q0ncFloo7CjRPwMnCWqKXQZ75El4nKC9dmcJaou9AXOE5UXbi+RGeJygrz8Uf+GewSn9uXuplnWDZJ7d8f24F/s6iq0LYf9olbS3Q8i5oKrRu4S9ybwaQ/aCkqtP3I28QDgeoK7TBya/aXqL5COx67PTCD2grtdOwH+pQV2r0a7YVBgZoKwwIVFQYG6ikMDVRTGByopjD8ATcKb0UhhRTe77sKs2DV7FKSjId18TUEBYVyLhUThWfILHTDqmI85/2RWWjcE/bhP6OD7maT3h20MHsA47JC3PsW0wcwLhv9t0OOPOIkCn21y2bXXwlyylxiYMPk1SuCSmpfK8bNQvIrpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwNX4BCbAju9/X67UAAAAASUVORK5CYII=" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
            </a>

            {% endblock %}
        </div>
    </div>
    <div style="height: 50px;"></div>
    <!-- END OF NAVBAR-->

    <div class="container text">
        {% if title %}

        <center>
            <p>{{title}}</p>
        </center>

        {% endif %}
        <!--<div class="container-fluid mt-5" style="max-width: 80%">-->
        <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
        {% block content %}
        {% endblock  %}
        {% block contato %}
        {% endblock  %}
        <script>
            function mudarModo1() {
                var modo = "{{isDarkMode}}"
                if (modo == "True") {
                    document.body.style.background = "#404040"
                    document.body.style.color = "#FFFFFF";
                }
                else {
                    document.body.style.background = "#FFFFFF";
                    document.body.style.color = "#404040";
                }
            }

            function mudarModo2() {
                var modo = "{{isMiopiaMode}}"
                if (modo == "True") {
                    document.body.style.fontSize = "2rem"
                }
                else {
                    document.body.style.fontSize = "1rem"
                }
            }
        </script>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

<a href="{% url 'psiu:ajuda' %}" class="btn position-absolute bottom end-0"><img src="https://media.discordapp.net/attachments/1004623388758777966/1044755829473161297/unknown.png" height="50" width="50"></a>

<a href="{% url 'psiu:logout' %}" class="btn position-absolute top-0 end-0">Sair da conta</a>
</html>
<!-- Towardsdatascience -->

templates/chatHome.html
{% extends 'baseChat.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<br>
    <form id="post-form" method="POST" action="checkview" class="form-group">
        {% csrf_token %}
        <div class="row form-row">
            <div class="col">
                <label>Sala</label>
                <input class="form-control" type="text" name="room_name" id="room_name" width="100px" />
            </div>
            
        </div>
<br>
                <input class="btn btn-primary" type="submit" value="Entrar">
    </form>

</body>


</html>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block image-page %}
<a href="{% url 'psiu:user_info' request.user.id %}">
    <img src="{{ user.perfil.fotoPerfil.url }}" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
</a>
{% endblock %}
{% block content %}

<!doctype html>
<html lang="pt-br">

    <center>
        <p>{{ user.first_name }} {{ user.last_name }}</p>   
    </center>
    
    <div class="container text-center">
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <a id="carona-link" class="btn btn-white" href="{% url 'psiu:carona' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1004623388758777966/1039839649834737725/Untitled-2.png" class="rounded-circle" height="100" width="100"></a>
                <br>Carona
            </div>
            <div class="col-1">
            </div>
            <div class="col">
                <a id="grupo-estudos-link" class="btn btn-white" href="{% url 'psiu:grupo_estudos' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1004623388758777966/1039835973950914570/Untitled-2.png" class="rounded-circle" height="100" width="100"></a>
                <br>Grupo de Estudos
            </div>
            <div class="col">
            </div>
        </div>
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <a id="extracurriculares-link" class="btn btn-white" href="{% url 'psiu:extracurriculares' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1004623388758777966/1039835618223607899/Untitled-2.png" class="rounded-circle" height="100" width="100"></a>
                <br>Atividades Extracurriculares
            </div>
            <div class="col-1">
            </div>
            <div class="col">
                <a id="ligas-academicas-link" class="btn btn-white" href="{% url 'psiu:ligas_academicas' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1004623388758777966/1039836952775622686/Untitled-2.png" class="rounded-circle" height="100" width="100"></a>
                <br>Ligas Acadêmicas
            </div>
            <div class="col">
            </div>
        </div>
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <a id="conhecer-pessoas-link" class="btn btn-white" href="{% url 'psiu:conhecer_pessoas' %}" role="button"><img src="https://cdn.discordapp.com/attachments/1004623388758777966/1039837525088403476/Untitled-2.png" class="rounded-circle" height="100" width="100"></a>
                <br>Conhecer Pessoas
            </div>
            <div class="col">
            </div>
        </div>
        <br>
        <div class="row">
        </div>
    </div>
</html>


{% endblock %}

templates/room.html
{% extends 'baseChat.html' %}

{% block image-page %}
<a href="{% url 'psiu:user_info' request.user.id %}">
    <img src="{{ user.perfil.fotoPerfil.url }}" class="mx-auto d-block rounded-circle position-absolute top-100 start-50 translate-middle" height="100" width="100" style="margin-top:23px">
</a>
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>

<h2>Chat</h2>

<div id="display">
</div>

<script>
$(document).ready(function(){

setInterval(function(){
    $.ajax({
        type: 'GET',
        url : "/psiuChat/getMessages/{{room}}/",
        success: function(response){
            console.log(response);
            $("#display").empty();
            for (var key in response.messages)
            {
                var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p></span></div>";
                $("#display").append(temp);
            }
        },
        error: function(response){
            alert('An error occured')
        }
    });
},1000);
})
</script>


<div class="container">
    <form id="post-form" class="form-group">
        {% csrf_token %}
        <input type="hidden" name="username" id="username" value="{{username}}"/>
        <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}"/>
        <input class="form-control" type="text" name="message" id="message" width="100px" />
        <br>
        <input  class="btn btn-primary" type="submit" value="Enviar">
    </form>
</div>


</body>

<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/psiuChat/send',
      data:{
          username:$('#username').val(),
          room_id:$('#room_id').val(),
          message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>

</html>
{% endblock %}